export type Tier = { id: string; title: string; description: string; minimumCents: number; perk: string }
export type Milestone = { percent: number; title: string; description: string; unlocked: boolean }
export type Campaign = { id: string; slug: string; title: string; category: string; location: string; tagline: string; story: string; creator: string; visual: string; goalCents: number; raisedCents: number; backerCount: number; percent: number; deadline: string; tiers: Tier[]; milestones: Milestone[] }
export const money = (cents: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(cents / 100)
export const daysLeft = (iso: string) => Math.max(0, Math.ceil((new Date(iso).getTime() - Date.now()) / 86400000))
const after = (days: number) => new Date(Date.now() + days * 86400000).toISOString()
export const demoCampaigns: Campaign[] = [
  { id: 'demo-wildwood', slug: 'wildwood-studio', title: 'Wildwood Studio', category: 'Design', location: 'Portland, OR', tagline: 'A neighborhood ceramics studio built for curious hands.', story: 'We are transforming an old storefront into a warm, accessible ceramics studio. Your support funds wheels, kilns, community classes, and a sliding scale membership for neighbors who need it.', creator: 'Maya Chen', visual: 'clay', goalCents: 2400000, raisedCents: 1632000, backerCount: 42, percent: 68, deadline: after(29),
    tiers: [{ id: 'spark', title: 'A little spark', description: 'A heartfelt thank-you and studio updates.', minimumCents: 2500, perk: 'Digital thank-you' }, { id: 'maker', title: 'The maker', description: 'Get your hands in clay at our opening workshop.', minimumCents: 7500, perk: 'Workshop seat' }, { id: 'founder', title: 'Founding member', description: 'A handmade mug and first access to classes.', minimumCents: 15000, perk: 'Handmade mug + early access' }],
    milestones: [{ percent: 25, title: 'First wheel funded', description: 'Our first pottery wheel is on its way.', unlocked: true }, { percent: 50, title: 'Community classes', description: 'Free introductory classes are unlocked.', unlocked: true }, { percent: 100, title: 'Doors open', description: 'The full studio buildout is funded.', unlocked: false }] },
  { id: 'demo-sunroom', slug: 'sunroom-press', title: 'Sunroom Press', category: 'Publishing', location: 'Brooklyn, NY', tagline: 'An independent print journal about the places we call home.', story: 'Sunroom is a tactile, independently published journal filled with stories, photography, and illustrations from emerging artists. Help us print issue one and pay every contributor fairly.', creator: 'Noah Rivera', visual: 'paper', goalCents: 1200000, raisedCents: 1092000, backerCount: 87, percent: 91, deadline: after(18),
    tiers: [{ id: 'reader', title: 'Early reader', description: 'A digital copy of issue one.', minimumCents: 1800, perk: 'Digital issue' }, { id: 'print', title: 'The print edition', description: 'A first-run copy delivered to your door.', minimumCents: 4500, perk: 'Print journal' }, { id: 'patron', title: 'Studio patron', description: 'Signed issue and an invite to our launch night.', minimumCents: 10000, perk: 'Signed issue + invite' }],
    milestones: [{ percent: 25, title: 'Writers commissioned', description: 'Our first stories can begin.', unlocked: true }, { percent: 75, title: 'Print run secured', description: 'Issue one is headed to the printer.', unlocked: true }, { percent: 100, title: 'Launch night', description: 'We celebrate our contributors together.', unlocked: false }] },
  { id: 'demo-moss', slug: 'moss-and-moon', title: 'Moss & Moon', category: 'Food & Drink', location: 'Austin, TX', tagline: 'Small-batch botanical sodas made for the long way home.', story: 'We blend familiar fruit with unexpected botanicals to make a soda worth slowing down for. This campaign helps us scale our first small batch and bring it to independent shops.', creator: 'Ari Williams', visual: 'citrus', goalCents: 3500000, raisedCents: 1470000, backerCount: 26, percent: 42, deadline: after(41),
    tiers: [{ id: 'taste', title: 'First taste', description: 'A thank-you and behind-the-scenes recipes.', minimumCents: 2000, perk: 'Recipe notes' }, { id: 'sixpack', title: 'The first six-pack', description: 'Try our launch flavors before anyone else.', minimumCents: 6000, perk: 'Six-pack' }, { id: 'table', title: 'At our table', description: 'A tasting night with the founders.', minimumCents: 20000, perk: 'Tasting invitation' }],
    milestones: [{ percent: 25, title: 'First batch', description: 'Ingredients and bottles are funded.', unlocked: true }, { percent: 50, title: 'Local delivery', description: 'We can stock our first partner shops.', unlocked: false }, { percent: 100, title: 'Cheers to everyone', description: 'The full launch is funded.', unlocked: false }] },
]
